### ISSUE TITLE
Unable to Login to xrmtb connection after installing Audit-History-Extractor

### ISSUE THREAD

**Issue by bryce2071** [alduzzen1985/Audit-History-Extractor#2]
Hi, 

after installing this plugin in xrmtb i wasnt able to Login to any of my 5 crm-systems ... "Unable to Login to Dynamics CRM".

I found the problem in the connection logs. 
I uninstalled your Plugin, then it works :-)

This was the error:
Error	: A proxy type with the name audit has been defined by another assembly. Current type: DLaB.Xrm.Entities.Audit, DLaB.Xrm.Entities, Version=8.1.0.1, Culture=neutral, PublicKeyToken=null, Existing type: AuditHistoryExtractor.AppCode.Audit, AuditHistoryExtractor, Version=1.0.1.9, Culture=neutral, PublicKeyToken=null
Parametername: audit

Thx, PeB

**Comment by MscrmTools** [comment]
You cannot use Early Bound Entities in your plugin. Please use Late Bound Entities instead.

It seems that this change (adding Early Bound Entities) has arrived with latest version. Could you please commit changes on Github before updating a version so that it is possible to review your changes and understand what is wrong

**Comment by alduzzen1985** [comment]
Problem Fixed
